import type { Locale } from "../../types";
const en = {
  pauseAnimation: "Pause animation",
  resumeAnimation: "Resume animation",
  title: "Find your next upgrade.",
  body: "Buy and sell PC components easily and safely.",
  browse: "Browse products",
  newest: "Latest listings",
  official: "Rigi's selection",
  officialBody: "Products listed by Rigi administrator accounts.",
  all: "View all",
  less: "Show less",
  moreOfficial: "More from Rigi",
  recommendations: "Recommended for you",
  explanation:
    "Based on your favourites, categories viewed during this visit, freshness and a varied selection. Your own listings are excluded.",
  more: "More recommendations",
  count: "products",
  limit: "That's this visit's selection. Refresh for a new mix.",
  empty: "No products for sale yet.",
  officialEmpty: "No products from Rigi for sale right now.",
  loading: "Loading products…",
  error: "Could not load products. Please try again.",
  retry: "Try again",
  trust: "Safer trading",
  payment: "Payment protection",
  paymentBody: "Coming with the payment service",
  verified: "Seller information",
  verifiedBody: "Review the seller and their feedback",
  shipping: "Rigi shipping",
  shippingBody: "Coming with shipping integration",
  safety: "Read our safety guide",
};
const fi: typeof en = {
  pauseAnimation: "Pysäytä animaatio",
  resumeAnimation: "Jatka animaatiota",
  title: "Löydä seuraava päivityksesi.",
  body: "Osta ja myy PC-komponentteja helposti ja turvallisesti.",
  browse: "Selaa tuotteita",
  newest: "Uusimmat ilmoitukset",
  official: "Rigin tarjonta",
  officialBody: "Rigin ylläpitäjätilien julkaisemat tuotteet.",
  all: "Näytä kaikki",
  less: "Näytä vähemmän",
  moreOfficial: "Lisää Rigin tarjontaa",
  recommendations: "Sinulle suositeltua",
  explanation:
    "Suosikkiesi, tällä vierailulla katsomiesi tuoteryhmien ja ilmoitusten tuoreuden perusteella. Mukana myös vaihtelua. Omia ilmoituksiasi ei suositella.",
  more: "Lisää suositeltuja",
  count: "tuotetta",
  limit: "Tämän vierailun valikoima on tässä. Päivittämällä sivun saat uutta vaihtelua.",
  empty: "Myynnissä ei ole vielä tuotteita.",
  officialEmpty: "Rigillä ei ole juuri nyt tuotteita myynnissä.",
  loading: "Ladataan tuotteita…",
  error: "Tuotteiden lataaminen epäonnistui. Yritä uudelleen.",
  retry: "Yritä uudelleen",
  trust: "Turvallinen kaupankäynti",
  payment: "Maksuturva",
  paymentBody: "Tulossa maksupalvelun yhteydessä",
  verified: "Myyjän tiedot",
  verifiedBody: "Tutustu myyjään ja palautteisiin",
  shipping: "Rigi-lähetys",
  shippingBody: "Tulossa toimituspalvelun yhteydessä",
  safety: "Lue turvallisuusohjeet",
};
const sv: typeof en = {
  pauseAnimation: "Pausa animationen",
  resumeAnimation: "Fortsätt animationen",
  title: "Hitta din nästa uppgradering.",
  body: "Köp och sälj datorkomponenter enkelt och tryggt.",
  browse: "Bläddra bland produkter",
  newest: "Senaste annonserna",
  official: "Rigis utbud",
  officialBody: "Produkter från Rigis administratörskonton.",
  all: "Visa alla",
  less: "Visa färre",
  moreOfficial: "Mer från Rigi",
  recommendations: "Rekommenderat för dig",
  explanation:
    "Utifrån dina favoriter, kategorier du besökt under detta besök, nya annonser och variation. Dina egna annonser utesluts.",
  more: "Fler rekommendationer",
  count: "produkter",
  limit: "Det här är besökets urval. Uppdatera sidan för ny variation.",
  empty: "Inga produkter till salu ännu.",
  officialEmpty: "Rigi har inga produkter till salu just nu.",
  loading: "Laddar produkter…",
  error: "Kunde inte ladda produkter. Försök igen.",
  retry: "Försök igen",
  trust: "Tryggare handel",
  payment: "Betalningsskydd",
  paymentBody: "Kommer med betaltjänsten",
  verified: "Säljarinformation",
  verifiedBody: "Granska säljaren och omdömen",
  shipping: "Rigi-frakt",
  shippingBody: "Kommer med frakttjänsten",
  safety: "Läs säkerhetsguiden",
};
export function getHomeCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
