import type { Locale } from "../../types";

const en = {
  title: "Admin Dashboard",
  overview: "Overview",
  navigation: "Admin navigation",
  market: "Finland · EUR",
  back: "Back to marketplace",
  content: "Content pages",
  description: "An overview of users, listings and transactions in the Finnish marketplace.",
  loginTitle: "Sign in to continue",
  loginBody: "This dashboard is available to administrators only.",
  login: "Sign in",
  deniedTitle: "Admin access required",
  deniedBody: "Your account does not have access to the Admin Dashboard.",
  setupTitle: "Dashboard requires a connected service",
  setupBody: "Admin metrics are available when the marketplace is connected to Supabase.",
  notFoundTitle: "Admin page not found",
  notFoundBody: "Open Overview to view the available admin dashboard.",
  loading: "Loading overview…",
  authLoading: "Checking your session…",
  errorTitle: "Overview could not be loaded",
  errorBody: "Please try again. If the issue persists, check the service configuration.",
  refresh: "Refresh",
  updated: "Updated",
  users: "Registered users",
  newUsers: "new in the last 7 days",
  activeListings: "Active listings",
  totalListings: "listings in total",
  completedOrders: "Completed orders",
  totalOrders: "orders in total",
  openReports: "Unresolved reports",
  reportsBody: "Reports awaiting review",
  listingStates: "Listing status",
  draft: "Draft",
  active: "Active",
  reserved: "Reserved",
  sold: "Sold",
  removed: "Removed",
  transactions: "Transactions",
  completedValue: "Completed item value",
  completedFees: "Fees on completed orders",
  disputes: "Disputed orders",
  moneyNote:
    "Amounts include completed EUR orders only. Item value excludes shipping and fees. Refunded and cancelled orders are excluded.",
  sourceNote: "Metrics come from the marketplace database. Local demo listings and purchases are excluded.",
};

const fi: typeof en = {
  title: "Admin Dashboard",
  overview: "Yleiskatsaus",
  navigation: "Ylläpidon navigaatio",
  market: "Suomi · EUR",
  back: "Takaisin markkinapaikalle",
  content: "Sisältösivut",
  description: "Yhteenveto Suomen markkinapaikan käyttäjistä, ilmoituksista ja kaupoista.",
  loginTitle: "Kirjaudu jatkaaksesi",
  loginBody: "Dashboard on tarkoitettu vain ylläpitäjille.",
  login: "Kirjaudu",
  deniedTitle: "Tarvitset ylläpitäjän oikeudet",
  deniedBody: "Tililläsi ei ole pääsyä Admin Dashboardiin.",
  setupTitle: "Dashboard tarvitsee palveluyhteyden",
  setupBody: "Ylläpidon mittarit ovat saatavilla, kun markkinapaikka on yhdistetty Supabaseen.",
  notFoundTitle: "Ylläpidon sivua ei löytynyt",
  notFoundBody: "Avaa yleiskatsaus nähdäksesi käytössä olevan Dashboardin.",
  loading: "Ladataan yleiskatsausta…",
  authLoading: "Tarkistetaan istuntoa…",
  errorTitle: "Yleiskatsausta ei voitu ladata",
  errorBody: "Yritä uudelleen. Jos ongelma jatkuu, tarkista palvelun asetukset.",
  refresh: "Päivitä",
  updated: "Päivitetty",
  users: "Rekisteröityneet käyttäjät",
  newUsers: "uutta viimeisen 7 päivän aikana",
  activeListings: "Aktiiviset ilmoitukset",
  totalListings: "ilmoitusta yhteensä",
  completedOrders: "Valmiit kaupat",
  totalOrders: "tilausta yhteensä",
  openReports: "Avoimet raportit",
  reportsBody: "Käsittelyä odottavat raportit",
  listingStates: "Ilmoitusten tilat",
  draft: "Luonnokset",
  active: "Aktiiviset",
  reserved: "Varatut",
  sold: "Myydyt",
  removed: "Poistetut",
  transactions: "Kaupankäynti",
  completedValue: "Valmiiden kauppojen tuotteiden arvo",
  completedFees: "Valmiiden kauppojen palvelumaksut",
  disputes: "Riitautetut tilaukset",
  moneyNote:
    "Summat sisältävät vain valmiit euromääräiset kaupat. Tuotteiden arvossa ei ole toimitus- eikä palvelumaksuja. Palautetut ja perutut tilaukset on rajattu pois.",
  sourceNote:
    "Luvut tulevat markkinapaikan tietokannasta. Paikalliset demoilmoitukset ja demo-ostot eivät sisälly niihin.",
};

const sv: typeof en = {
  title: "Admin Dashboard",
  overview: "Översikt",
  navigation: "Administrationsmeny",
  market: "Finland · EUR",
  back: "Tillbaka till marknadsplatsen",
  content: "Innehållssidor",
  description: "En översikt över användare, annonser och affärer på den finska marknadsplatsen.",
  loginTitle: "Logga in för att fortsätta",
  loginBody: "Dashboarden är endast tillgänglig för administratörer.",
  login: "Logga in",
  deniedTitle: "Administratörsbehörighet krävs",
  deniedBody: "Ditt konto har inte tillgång till Admin Dashboard.",
  setupTitle: "Dashboarden kräver en tjänsteanslutning",
  setupBody: "Administrationsstatistik är tillgänglig när marknadsplatsen är ansluten till Supabase.",
  notFoundTitle: "Administrationssidan hittades inte",
  notFoundBody: "Öppna översikten för att se den tillgängliga dashboarden.",
  loading: "Laddar översikten…",
  authLoading: "Kontrollerar sessionen…",
  errorTitle: "Översikten kunde inte laddas",
  errorBody: "Försök igen. Kontrollera tjänstens inställningar om problemet kvarstår.",
  refresh: "Uppdatera",
  updated: "Uppdaterad",
  users: "Registrerade användare",
  newUsers: "nya under de senaste 7 dagarna",
  activeListings: "Aktiva annonser",
  totalListings: "annonser totalt",
  completedOrders: "Slutförda affärer",
  totalOrders: "beställningar totalt",
  openReports: "Olösta rapporter",
  reportsBody: "Rapporter som väntar på granskning",
  listingStates: "Annonsstatus",
  draft: "Utkast",
  active: "Aktiva",
  reserved: "Reserverade",
  sold: "Sålda",
  removed: "Borttagna",
  transactions: "Handel",
  completedValue: "Varuvärde för slutförda affärer",
  completedFees: "Avgifter för slutförda affärer",
  disputes: "Tvistiga beställningar",
  moneyNote:
    "Beloppen omfattar endast slutförda affärer i euro. Varuvärdet exkluderar frakt och avgifter. Återbetalda och avbrutna beställningar är exkluderade.",
  sourceNote: "Statistiken kommer från marknadsplatsens databas. Lokala demoannonser och demoköp är exkluderade.",
};

export function getAdminCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
