import type { Locale } from "../../types";

const en = {
  resolve: "Mark resolved",
  reopen: "Reopen report",
  decisionNote: "Reason for decision (10–2000 characters)",
  decisionHelp: "The decision and your user ID are recorded. The listing remains unchanged.",
  saving: "Saving…",
  saved: "Decision saved.",
  saveError: "Could not confirm saving. Refresh the list before retrying.",
  conflict: "Another decision has changed this report. Refresh the list before continuing.",
  lastDecision: "Latest decision",
  reviewer: "Reviewer",
  title: "Reports",
  description: "Review and resolve listing reports from the Finnish marketplace.",
  search: "Search by listing title or full report, listing or reporter ID",
  submit: "Search",
  status: "Status",
  open: "Open",
  resolved: "Resolved",
  all: "All reports",
  listing: "Listing",
  reporter: "Reporter",
  seller: "Seller",
  reason: "Reason",
  details: "Details",
  created: "Submitted",
  resolvedAt: "Resolved",
  empty: "No matching reports.",
  total: "Matching reports",
  previous: "Previous",
  next: "Next",
  page: "Page",
  loading: "Loading reports…",
  error: "Reports could not be loaded.",
  reasons: { misleading: "Misleading", prohibited: "Prohibited item", scam: "Suspected scam", other: "Other" },
};
const fi: typeof en = {
  resolve: "Merkitse käsitellyksi",
  reopen: "Avaa raportti uudelleen",
  decisionNote: "Päätöksen perustelu (10–2000 merkkiä)",
  decisionHelp: "Päätös ja käyttäjätunnisteesi tallennetaan. Ilmoitus säilyy ennallaan.",
  saving: "Tallennetaan…",
  saved: "Päätös tallennettu.",
  saveError: "Tallennusta ei voitu varmistaa. Päivitä lista ennen uutta yritystä.",
  conflict: "Raporttia on jo käsitelty toisessa näkymässä. Päivitä lista ennen jatkamista.",
  lastDecision: "Viimeisin päätös",
  reviewer: "Käsittelijä",
  title: "Raportit",
  description: "Tarkista ja käsittele Suomen markkinapaikan ilmoitusraportteja.",
  search: "Hae ilmoituksen otsikolla tai täydellä raportti-, ilmoitus- tai raportoijatunnisteella",
  submit: "Hae",
  status: "Tila",
  open: "Avoin",
  resolved: "Käsitelty",
  all: "Kaikki raportit",
  listing: "Ilmoitus",
  reporter: "Raportoija",
  seller: "Myyjä",
  reason: "Syy",
  details: "Lisätiedot",
  created: "Lähetetty",
  resolvedAt: "Käsitelty",
  empty: "Hakua vastaavia raportteja ei löytynyt.",
  total: "Hakua vastaavia raportteja",
  previous: "Edellinen",
  next: "Seuraava",
  page: "Sivu",
  loading: "Ladataan raportteja…",
  error: "Raportteja ei voitu ladata.",
  reasons: { misleading: "Harhaanjohtava", prohibited: "Kielletty tuote", scam: "Petosepäily", other: "Muu" },
};
const sv: typeof en = {
  resolve: "Markera som behandlad",
  reopen: "Öppna rapporten igen",
  decisionNote: "Motivering (10–2000 tecken)",
  decisionHelp: "Beslutet och ditt användar-ID sparas. Annonsen förblir oförändrad.",
  saving: "Sparar…",
  saved: "Beslutet sparades.",
  saveError: "Det gick inte att bekräfta sparandet. Uppdatera listan före nästa försök.",
  conflict: "Rapporten har ändrats i en annan vy. Uppdatera listan innan du fortsätter.",
  lastDecision: "Senaste beslut",
  reviewer: "Handläggare",
  title: "Rapporter",
  description: "Granska och behandla annonsrapporter från den finska marknadsplatsen.",
  search: "Sök med annonsrubrik eller fullständigt rapport-, annons- eller anmälar-ID",
  submit: "Sök",
  status: "Status",
  open: "Öppen",
  resolved: "Behandlad",
  all: "Alla rapporter",
  listing: "Annons",
  reporter: "Anmälare",
  seller: "Säljare",
  reason: "Orsak",
  details: "Detaljer",
  created: "Skickad",
  resolvedAt: "Behandlad",
  empty: "Inga matchande rapporter.",
  total: "Matchande rapporter",
  previous: "Föregående",
  next: "Nästa",
  page: "Sida",
  loading: "Laddar rapporter…",
  error: "Rapporterna kunde inte laddas.",
  reasons: { misleading: "Vilseledande", prohibited: "Förbjuden vara", scam: "Misstänkt bedrägeri", other: "Annat" },
};
export function getAdminReportsCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
