import type { Locale } from "../../types";
const en = {
  title: "Listings",
  description: "Finnish marketplace listings and available moderation actions.",
  search: "Search by title, full listing ID or seller ID",
  submit: "Search",
  status: "Status",
  all: "All states",
  listing: "Listing",
  seller: "Seller",
  price: "Price",
  created: "Created",
  empty: "No matching listings.",
  total: "Matching listings",
  previous: "Previous",
  next: "Next",
  page: "Page",
  loading: "Loading listings…",
  error: "Listings could not be loaded.",
  moderation: "Moderation",
  reason: "Reason (10–2000 characters)",
  hide: "Hide listing",
  restore: "Restore listing",
  saving: "Saving…",
  saved: "Moderation decision saved.",
  conflict: "Listing changed. Refresh before deciding.",
  order: "An active order prevents hiding this listing.",
};
const fi: typeof en = {
  title: "Ilmoitukset",
  description: "Suomen markkinapaikan ilmoitukset ja käytettävissä olevat moderointitoimet.",
  search: "Hae otsikolla, koko ilmoitus- tai myyjätunnisteella",
  submit: "Hae",
  status: "Tila",
  all: "Kaikki tilat",
  listing: "Ilmoitus",
  seller: "Myyjä",
  price: "Hinta",
  created: "Luotu",
  empty: "Hakua vastaavia ilmoituksia ei löytynyt.",
  total: "Hakua vastaavia ilmoituksia",
  previous: "Edellinen",
  next: "Seuraava",
  page: "Sivu",
  loading: "Ladataan ilmoituksia…",
  error: "Ilmoituksia ei voitu ladata.",
  moderation: "Moderointi",
  reason: "Perustelu (10–2000 merkkiä)",
  hide: "Piilota ilmoitus",
  restore: "Palauta ilmoitus",
  saving: "Tallennetaan…",
  saved: "Moderointipäätös tallennettu.",
  conflict: "Ilmoitus muuttui. Päivitä ennen päätöstä.",
  order: "Aktiivinen tilaus estää ilmoituksen piilottamisen.",
};
const sv: typeof en = {
  title: "Annonser",
  description: "Annonser i Finland och tillgängliga modereringsåtgärder.",
  search: "Sök med rubrik, fullständigt annons-ID eller säljar-ID",
  submit: "Sök",
  status: "Status",
  all: "Alla statusar",
  listing: "Annons",
  seller: "Säljare",
  price: "Pris",
  created: "Skapad",
  empty: "Inga matchande annonser.",
  total: "Matchande annonser",
  previous: "Föregående",
  next: "Nästa",
  page: "Sida",
  loading: "Laddar annonser…",
  error: "Annonserna kunde inte laddas.",
  moderation: "Moderering",
  reason: "Motivering (10–2000 tecken)",
  hide: "Dölj annons",
  restore: "Återställ annons",
  saving: "Sparar…",
  saved: "Moderationsbeslutet sparades.",
  conflict: "Annonsen har ändrats. Uppdatera före beslutet.",
  order: "En aktiv beställning hindrar att annonsen döljs.",
};
export function getAdminListingsCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
