import type { Locale } from "../../types";

const en = {
  title: "Reports",
  description: "Listing reports from the Finnish marketplace. Review queue; no moderation actions yet.",
  search: "Search by listing title or full report, listing or reporter ID",
  submit: "Search",
  status: "Status",
  open: "Open",
  resolved: "Resolved",
  all: "All reports",
  listing: "Listing",
  reporter: "Reporter",
  seller: "Seller",
  reason: "Reason",
  details: "Details",
  created: "Submitted",
  resolvedAt: "Resolved",
  empty: "No matching reports.",
  total: "Matching reports",
  previous: "Previous",
  next: "Next",
  page: "Page",
  loading: "Loading reports…",
  error: "Reports could not be loaded.",
  reasons: { misleading: "Misleading", prohibited: "Prohibited item", scam: "Suspected scam", other: "Other" },
};
const fi: typeof en = {
  title: "Raportit",
  description: "Suomen markkinapaikan ilmoitusraportit. Katselujono; moderointitoimet lisätään myöhemmin.",
  search: "Hae ilmoituksen otsikolla tai täydellä raportti-, ilmoitus- tai raportoijatunnisteella",
  submit: "Hae",
  status: "Tila",
  open: "Avoin",
  resolved: "Käsitelty",
  all: "Kaikki raportit",
  listing: "Ilmoitus",
  reporter: "Raportoija",
  seller: "Myyjä",
  reason: "Syy",
  details: "Lisätiedot",
  created: "Lähetetty",
  resolvedAt: "Käsitelty",
  empty: "Hakua vastaavia raportteja ei löytynyt.",
  total: "Hakua vastaavia raportteja",
  previous: "Edellinen",
  next: "Seuraava",
  page: "Sivu",
  loading: "Ladataan raportteja…",
  error: "Raportteja ei voitu ladata.",
  reasons: { misleading: "Harhaanjohtava", prohibited: "Kielletty tuote", scam: "Petosepäily", other: "Muu" },
};
const sv: typeof en = {
  title: "Rapporter",
  description: "Annonsrapporter från den finska marknadsplatsen. Läsbar granskningskö.",
  search: "Sök med annonsrubrik eller fullständigt rapport-, annons- eller anmälar-ID",
  submit: "Sök",
  status: "Status",
  open: "Öppen",
  resolved: "Behandlad",
  all: "Alla rapporter",
  listing: "Annons",
  reporter: "Anmälare",
  seller: "Säljare",
  reason: "Orsak",
  details: "Detaljer",
  created: "Skickad",
  resolvedAt: "Behandlad",
  empty: "Inga matchande rapporter.",
  total: "Matchande rapporter",
  previous: "Föregående",
  next: "Nästa",
  page: "Sida",
  loading: "Laddar rapporter…",
  error: "Rapporterna kunde inte laddas.",
  reasons: { misleading: "Vilseledande", prohibited: "Förbjuden vara", scam: "Misstänkt bedrägeri", other: "Annat" },
};
export function getAdminReportsCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
