import type { Locale } from "../../types";

const en = {
  title: "Marketing",
  description: "Publish a short announcement on the home page in the selected language.",
  announcement: "Announcement",
  add: "New announcement",
  edit: "Edit",
  cancel: "Cancel",
  save: "Save announcement",
  saving: "Saving…",
  titleLabel: "Title",
  bodyLabel: "Message",
  language: "Language",
  published: "Published",
  draft: "Draft",
  publish: "Show on the home page",
  empty: "No announcements yet.",
  loading: "Loading announcements…",
  error: "Announcements could not be loaded.",
  saveError: "Announcement could not be saved.",
  conflict: "Announcement changed. Refresh before editing.",
  saved: "Announcement saved.",
  note: "The most recently updated published announcement is shown for each language. This does not change prices or checkout.",
};
const fi: typeof en = {
  title: "Markkinointi",
  description: "Julkaise lyhyt tiedote etusivulle valitulla kielellä.",
  announcement: "Tiedote",
  add: "Uusi tiedote",
  edit: "Muokkaa",
  cancel: "Peruuta",
  save: "Tallenna tiedote",
  saving: "Tallennetaan…",
  titleLabel: "Otsikko",
  bodyLabel: "Viesti",
  language: "Kieli",
  published: "Julkaistu",
  draft: "Luonnos",
  publish: "Näytä etusivulla",
  empty: "Tiedotteita ei ole vielä.",
  loading: "Ladataan tiedotteita…",
  error: "Tiedotteita ei voitu ladata.",
  saveError: "Tiedotetta ei voitu tallentaa.",
  conflict: "Tiedote muuttui. Päivitä sivu ennen muokkausta.",
  saved: "Tiedote tallennettu.",
  note: "Kunkin kielen viimeksi päivitetty julkaistu tiedote näkyy etusivulla. Tämä ei muuta hintoja tai kassaa.",
};
const sv: typeof en = {
  title: "Marknadsföring",
  description: "Publicera ett kort meddelande på startsidan på valt språk.",
  announcement: "Meddelande",
  add: "Nytt meddelande",
  edit: "Redigera",
  cancel: "Avbryt",
  save: "Spara meddelande",
  saving: "Sparar…",
  titleLabel: "Rubrik",
  bodyLabel: "Text",
  language: "Språk",
  published: "Publicerad",
  draft: "Utkast",
  publish: "Visa på startsidan",
  empty: "Inga meddelanden ännu.",
  loading: "Laddar meddelanden…",
  error: "Meddelandena kunde inte laddas.",
  saveError: "Meddelandet kunde inte sparas.",
  conflict: "Meddelandet har ändrats. Uppdatera sidan före redigering.",
  saved: "Meddelandet sparades.",
  note: "Det senast uppdaterade publicerade meddelandet visas för varje språk. Detta ändrar inte priser eller kassan.",
};

export function marketingCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
