import type { Locale } from "../../types";
const en = {
  title: "Listings",
  description: "Finnish marketplace listings in all states. Read-only view.",
  search: "Search by title, full listing ID or seller ID",
  submit: "Search",
  status: "Status",
  all: "All states",
  listing: "Listing",
  seller: "Seller",
  price: "Price",
  created: "Created",
  empty: "No matching listings.",
  total: "Matching listings",
  previous: "Previous",
  next: "Next",
  page: "Page",
  loading: "Loading listings…",
  error: "Listings could not be loaded.",
};
const fi: typeof en = {
  title: "Ilmoitukset",
  description: "Suomen markkinapaikan ilmoitukset kaikissa tiloissa. Katselunäkymä.",
  search: "Hae otsikolla, koko ilmoitus- tai myyjätunnisteella",
  submit: "Hae",
  status: "Tila",
  all: "Kaikki tilat",
  listing: "Ilmoitus",
  seller: "Myyjä",
  price: "Hinta",
  created: "Luotu",
  empty: "Hakua vastaavia ilmoituksia ei löytynyt.",
  total: "Hakua vastaavia ilmoituksia",
  previous: "Edellinen",
  next: "Seuraava",
  page: "Sivu",
  loading: "Ladataan ilmoituksia…",
  error: "Ilmoituksia ei voitu ladata.",
};
const sv: typeof en = {
  title: "Annonser",
  description: "Den finska marknadsplatsens annonser i alla statusar. Skrivskyddad vy.",
  search: "Sök med rubrik, fullständigt annons-ID eller säljar-ID",
  submit: "Sök",
  status: "Status",
  all: "Alla statusar",
  listing: "Annons",
  seller: "Säljare",
  price: "Pris",
  created: "Skapad",
  empty: "Inga matchande annonser.",
  total: "Matchande annonser",
  previous: "Föregående",
  next: "Nästa",
  page: "Sida",
  loading: "Laddar annonser…",
  error: "Annonserna kunde inte laddas.",
};
export function getAdminListingsCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
