import type { Locale } from "../../types";

const en = {
  title: "Product prices",
  category: "Product category",
  search: "Search catalog",
  products: "Choose a product",
  empty: "No catalog products match this search.",
  loading: "Loading…",
  error: "Could not load data. Try refreshing.",
  refresh: "Refresh",
  previous: "Previous",
  next: "Next",
  archived: "Archived",
  sales: "Completed sales",
  average: "Average price",
  change: "Average price change",
  percent: "Change %",
  curve: "Realized prices · daily average",
  note: "FI / EUR. Completed orders by order creation date; refunds can change the history. Days without sales are left empty. Only listings linked to this catalog model are included.",
  comparison: "Compared with the preceding equally long calendar period. Today is partial.",
  previousAverage: "Previous average",
  allTime: "All-time sales",
  noComparison: "No comparison sample",
  catalog: "Edit catalog",
};
const fi: typeof en = {
  title: "Tuotteiden hintakehitys",
  category: "Tuotekategoria",
  search: "Hae katalogista",
  products: "Valitse tuote",
  empty: "Haulla ei löytynyt katalogituotteita.",
  loading: "Ladataan…",
  error: "Tietoja ei voitu ladata. Kokeile päivittää.",
  refresh: "Päivitä",
  previous: "Edellinen",
  next: "Seuraava",
  archived: "Arkistoitu",
  sales: "Toteutuneet kaupat",
  average: "Keskihinta",
  change: "Keskihinnan muutos €",
  percent: "Keskihinnan muutos %",
  curve: "Toteutuneet hinnat · päivän keskihinta",
  note: "FI / EUR. Valmiit kaupat tilauksen luontipäivän mukaan; hyvitykset voivat muuttaa historiaa. Päivät ilman kauppoja ovat tyhjiä. Mukana ovat vain tähän katalogimalliin liitetyt ilmoitukset.",
  comparison: "Vertailuna edellinen yhtä pitkä kalenterijakso. Kuluva päivä on vielä kesken.",
  previousAverage: "Edellinen keskihinta",
  allTime: "Kauppoja kaikkiaan",
  noComparison: "Ei vertailuhavaintoja",
  catalog: "Muokkaa katalogia",
};
const sv: typeof en = {
  title: "Produkternas prisutveckling",
  category: "Produktkategori",
  search: "Sök i katalogen",
  products: "Välj produkt",
  empty: "Inga katalogprodukter matchar sökningen.",
  loading: "Laddar…",
  error: "Kunde inte läsa data. Försök uppdatera.",
  refresh: "Uppdatera",
  previous: "Föregående",
  next: "Nästa",
  archived: "Arkiverad",
  sales: "Slutförda affärer",
  average: "Genomsnittspris",
  change: "Prisförändring €",
  percent: "Prisförändring %",
  curve: "Försäljningspriser · dagligt genomsnitt",
  note: "FI / EUR. Slutförda affärer efter beställningsdatum; återbetalningar kan ändra historiken. Dagar utan affärer lämnas tomma. Endast annonser kopplade till katalogmodellen ingår.",
  comparison: "Jämfört med föregående lika långa kalenderperiod. Dagens värden är ofullständiga.",
  previousAverage: "Föregående genomsnitt",
  allTime: "Affärer totalt",
  noComparison: "Inga jämförelsevärden",
  catalog: "Redigera katalogen",
};
export const modelChartCopy = (locale: Locale) => (locale === "fi" ? fi : locale === "sv" ? sv : en);
