import type { Locale } from "../../types";
const en = {
  attention: "Requires attention",
  attentionNote: "Current queues, independent of the selected period.",
  missing: "Payment failures, payout release and shipping alerts require connected payment and delivery services.",
  activity: "Activity by period",
  period: "Period",
  custom: "Custom",
  apply: "Apply period",
  start: "From (UTC)",
  end: "Until (UTC)",
  invalid: "Choose a valid past period of at most 366 days.",
  previous: "Previous period",
  change: "Change",
  metric: "Metric",
  current: "Selected period",
  users: "New users",
  listings: "New listings",
  orders: "Orders created",
  completed: "Of these, currently completed",
  value: "Their item value",
  fees: "Their marketplace fees",
  note: "Orders are grouped by creation time and their current status, not payment or completion time. Changes in status can change past totals. Comparison uses the immediately preceding period of equal duration. All amounts are FI/EUR.",
  audit: "Audit log",
  auditNote:
    "Recorded catalog changes and report decisions. Other actions are not yet included. This view cannot edit or delete events.",
  search: "Target / actor / event ID, target type or action",
  empty: "No recorded events match this search.",
  actor: "Actor",
  target: "Target",
  time: "Time",
  action: "Action",
  details: "Change details",
  before: "Before",
  after: "After",
  reason: "Reason",
  noReason: "No reason recorded",
  noBefore: "No previous value",
  created: "Created",
  updated: "Updated",
  resolve: "Report resolved",
  reopen: "Report reopened",
};
const fi: typeof en = {
  attention: "Vaatii huomiota",
  attentionNote: "Tämänhetkiset työjonot, riippumatta valitusta aikavälistä.",
  missing:
    "Maksuvirheet, tilitysten vapautus ja toimitushälytykset edellyttävät maksu- ja toimituspalvelujen yhdistämistä.",
  activity: "Tapahtumat aikavälillä",
  period: "Aikaväli",
  custom: "Oma aikaväli",
  apply: "Näytä aikaväli",
  start: "Alkaen (UTC)",
  end: "Päättyen (UTC)",
  invalid: "Valitse kelvollinen mennyt aikaväli, enintään 366 päivää.",
  previous: "Edellinen jakso",
  change: "Muutos",
  metric: "Mittari",
  current: "Valittu jakso",
  users: "Uudet käyttäjät",
  listings: "Uudet ilmoitukset",
  orders: "Luodut tilaukset",
  completed: "Näistä tällä hetkellä valmiita",
  value: "Niiden tuotteiden arvo",
  fees: "Niiden palvelumaksut",
  note: "Tilaukset ryhmitellään luontiajan ja nykyisen tilan mukaan, ei maksu- tai valmistumisajan mukaan. Tilamuutokset voivat muuttaa menneitä lukuja. Vertailussa on välittömästi edeltävä samanpituinen jakso. Summat koskevat Suomen euromääräisiä kauppoja.",
  audit: "Tapahtumaloki",
  auditNote:
    "Tallennetut katalogimuutokset ja raporttien käsittelypäätökset. Muut toiminnot eivät vielä sisälly lokiin. Tästä näkymästä tapahtumia ei voi muokata tai poistaa.",
  search: "Kohteen / tekijän / tapahtuman tunnus, kohdetyyppi tai toiminto",
  empty: "Hakua vastaavia tallennettuja tapahtumia ei ole.",
  actor: "Tekijä",
  target: "Kohde",
  time: "Aika",
  action: "Toiminto",
  details: "Muutoksen tiedot",
  before: "Ennen",
  after: "Jälkeen",
  reason: "Perustelu",
  noReason: "Perustelua ei ole tallennettu",
  noBefore: "Ei aiempaa arvoa",
  created: "Luotu",
  updated: "Muokattu",
  resolve: "Raportti ratkaistu",
  reopen: "Raportti avattu uudelleen",
};
const sv: typeof en = {
  attention: "Kräver uppmärksamhet",
  attentionNote: "Aktuella köer, oberoende av vald period.",
  missing: "Betalningsfel, utbetalningar och leveransvarningar kräver anslutna betalnings- och leveranstjänster.",
  activity: "Aktivitet per period",
  period: "Period",
  custom: "Egen period",
  apply: "Visa period",
  start: "Från (UTC)",
  end: "Till (UTC)",
  invalid: "Välj en giltig tidigare period på högst 366 dagar.",
  previous: "Föregående period",
  change: "Förändring",
  metric: "Mått",
  current: "Vald period",
  users: "Nya användare",
  listings: "Nya annonser",
  orders: "Skapade beställningar",
  completed: "Av dessa, nu slutförda",
  value: "Deras varuvärde",
  fees: "Deras marknadsplatsavgifter",
  note: "Beställningar grupperas efter skapandetid och aktuell status, inte betalnings- eller sluttid. Statusändringar kan ändra historiska belopp. Jämförelsen gäller föregående lika långa period. Alla belopp gäller FI/EUR.",
  audit: "Händelselogg",
  auditNote:
    "Registrerade katalogändringar och rapportbeslut. Andra åtgärder ingår ännu inte. Händelser kan inte redigeras eller raderas i denna vy.",
  search: "Målets / aktörens / händelsens ID, måltyp eller åtgärd",
  empty: "Inga registrerade händelser matchar sökningen.",
  actor: "Aktör",
  target: "Mål",
  time: "Tid",
  action: "Åtgärd",
  details: "Ändringsdetaljer",
  before: "Före",
  after: "Efter",
  reason: "Motivering",
  noReason: "Ingen motivering registrerad",
  noBefore: "Inget tidigare värde",
  created: "Skapad",
  updated: "Uppdaterad",
  resolve: "Rapport löst",
  reopen: "Rapport återöppnad",
};
export const activityCopy = (locale: Locale) => (locale === "fi" ? fi : locale === "sv" ? sv : en);
