import type { Locale } from "../../types";

const en = {
  title: "Users",
  description: "Profiles registered in the Finnish marketplace.",
  search: "Search by display name or full user ID",
  submit: "Search",
  name: "Display name",
  role: "Role",
  joined: "Joined",
  language: "Language",
  id: "User ID",
  admin: "Administrator",
  user: "User",
  empty: "No matching profiles.",
  previous: "Previous",
  next: "Next",
  page: "Page",
  total: "Matching profiles",
  loading: "Loading users…",
  error: "Users could not be loaded.",
};
const fi: typeof en = {
  title: "Käyttäjät",
  description: "Suomen markkinapaikalle rekisteröidyt profiilit.",
  search: "Hae näyttönimellä tai koko käyttäjätunnisteella",
  submit: "Hae",
  name: "Näyttönimi",
  role: "Rooli",
  joined: "Liittynyt",
  language: "Kieli",
  id: "Käyttäjätunniste",
  admin: "Ylläpitäjä",
  user: "Käyttäjä",
  empty: "Hakua vastaavia profiileja ei löytynyt.",
  previous: "Edellinen",
  next: "Seuraava",
  page: "Sivu",
  total: "Hakua vastaavia profiileja",
  loading: "Ladataan käyttäjiä…",
  error: "Käyttäjiä ei voitu ladata.",
};
const sv: typeof en = {
  title: "Användare",
  description: "Profiler registrerade på den finska marknadsplatsen.",
  search: "Sök med visningsnamn eller fullständigt användar-ID",
  submit: "Sök",
  name: "Visningsnamn",
  role: "Roll",
  joined: "Registrerad",
  language: "Språk",
  id: "Användar-ID",
  admin: "Administratör",
  user: "Användare",
  empty: "Inga matchande profiler.",
  previous: "Föregående",
  next: "Nästa",
  page: "Sida",
  total: "Matchande profiler",
  loading: "Laddar användare…",
  error: "Användarna kunde inte laddas.",
};
export function getAdminUsersCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
