import type { Locale } from "../../types";
const en = {
  title: "Transactions",
  description: "Orders stored in the Finnish marketplace database. Demo purchases are excluded. Read-only view.",
  search: "Search by listing title or full order, listing, buyer or seller ID",
  submit: "Search",
  status: "Status",
  all: "All states",
  transaction: "Order / listing",
  buyer: "Buyer",
  seller: "Seller",
  price: "Order total",
  created: "Created",
  breakdown: "Price breakdown and listing ID",
  item: "Item",
  fee: "Marketplace fee",
  processing: "Payment processing",
  shipping: "Shipping",
  listingId: "Listing ID",
  empty: "No matching orders. Demo purchases are not stored here.",
  total: "Matching orders",
  previous: "Previous",
  next: "Next",
  page: "Page",
  loading: "Loading orders…",
  error: "Orders could not be loaded.",
  pending_payment: "Awaiting payment",
  paid: "Paid",
  shipped: "Shipped",
  delivered: "Delivered",
  inspection: "Inspection",
  disputed: "Disputed",
  completed: "Completed",
  refunded: "Refunded",
  cancelled: "Cancelled",
};
const fi: typeof en = {
  title: "Tilaukset",
  description:
    "Suomen markkinapaikan tietokantaan tallennetut tilaukset. Demo-ostot eivät sisälly listaan. Katselunäkymä.",
  search: "Hae ilmoituksen otsikolla tai koko tilaus-, ilmoitus-, ostaja- tai myyjätunnisteella",
  submit: "Hae",
  status: "Tila",
  all: "Kaikki tilat",
  transaction: "Tilaus / ilmoitus",
  buyer: "Ostaja",
  seller: "Myyjä",
  price: "Tilauksen kokonaissumma",
  created: "Luotu",
  breakdown: "Hintaerittely ja ilmoitustunniste",
  item: "Tuote",
  fee: "Palvelumaksu",
  processing: "Maksunkäsittely",
  shipping: "Toimitus",
  listingId: "Ilmoitustunniste",
  empty: "Hakua vastaavia tilauksia ei löytynyt. Demo-ostot eivät tallennu tänne.",
  total: "Hakua vastaavia tilauksia",
  previous: "Edellinen",
  next: "Seuraava",
  page: "Sivu",
  loading: "Ladataan tilauksia…",
  error: "Tilauksia ei voitu ladata.",
  pending_payment: "Odottaa maksua",
  paid: "Maksettu",
  shipped: "Lähetetty",
  delivered: "Toimitettu",
  inspection: "Tarkastuksessa",
  disputed: "Riitautettu",
  completed: "Valmis",
  refunded: "Hyvitetty",
  cancelled: "Peruttu",
};
const sv: typeof en = {
  title: "Beställningar",
  description: "Beställningar i den finska marknadsplatsens databas. Demoköp ingår inte. Skrivskyddad vy.",
  search: "Sök med annonsrubrik eller fullständigt beställnings-, annons-, köpar- eller säljar-ID",
  submit: "Sök",
  status: "Status",
  all: "Alla statusar",
  transaction: "Beställning / annons",
  buyer: "Köpare",
  seller: "Säljare",
  price: "Beställningens totalsumma",
  created: "Skapad",
  breakdown: "Prisspecifikation och annons-ID",
  item: "Vara",
  fee: "Serviceavgift",
  processing: "Betalningshantering",
  shipping: "Frakt",
  listingId: "Annons-ID",
  empty: "Inga matchande beställningar. Demoköp sparas inte här.",
  total: "Matchande beställningar",
  previous: "Föregående",
  next: "Nästa",
  page: "Sida",
  loading: "Laddar beställningar…",
  error: "Beställningarna kunde inte laddas.",
  pending_payment: "Väntar på betalning",
  paid: "Betald",
  shipped: "Skickad",
  delivered: "Levererad",
  inspection: "Inspektion",
  disputed: "Tvist",
  completed: "Slutförd",
  refunded: "Återbetald",
  cancelled: "Avbruten",
};
export function getAdminTransactionsCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
