import type { Locale } from "../../types";
const en = {
  title: "Product catalog",
  search: "Search models",
  hint: "Search by model or manufacturer. Select the exact version; you can also enter a product manually.",
  selected: "Catalog model selected",
  clear: "Use manual entry",
  empty: "No matching models. You can enter the details manually.",
  loading: "Loading models…",
  error: "Catalog could not be loaded. Try again or enter the details manually.",
  previous: "Previous",
  next: "Next",
  brand: "Manufacturer",
  name: "Model",
  variant: "Version / capacity / part number",
  aliases: "Alternative search terms",
  active: "Available in listing search",
  save: "Save model",
  add: "Add a model",
  edit: "Edit",
  cancel: "Cancel",
  saved: "Model saved.",
  failed:
    "Saving failed. Check the fields and duplicate models. If another administrator edited this model, reload it.",
  category: "Category",
  note: "Three starter models per category. Add precise variants separately. Statistics use explicitly linked listings and current completed orders in FI/EUR, across all time. Prices exclude shipping and fees. Condition and configuration may differ; PC series do not identify a complete configuration.",
  unlinked: "Active listings without a model",
  asking: "Active / average ask",
  sold: "Completed / average sale",
  noData: "No data",
  disabled: "Hidden",
  manual: "No automatic matching is made from old titles.",
};
const fi: typeof en = {
  title: "Tuotekatalogi",
  search: "Hae tuotemallia",
  hint: "Hae mallilla tai valmistajalla. Valitse oikea versio; voit myös täyttää tuotteen tiedot käsin.",
  selected: "Katalogimalli valittu",
  clear: "Syötä tiedot käsin",
  empty: "Malleja ei löytynyt. Voit täyttää tiedot käsin.",
  loading: "Ladataan malleja…",
  error: "Katalogia ei voitu ladata. Yritä uudelleen tai täytä tiedot käsin.",
  previous: "Edellinen",
  next: "Seuraava",
  brand: "Valmistaja",
  name: "Malli",
  variant: "Versio / kapasiteetti / osanumero",
  aliases: "Vaihtoehtoiset hakusanat",
  active: "Valittavissa ilmoitusta luotaessa",
  save: "Tallenna malli",
  add: "Lisää malli",
  edit: "Muokkaa",
  cancel: "Peruuta",
  saved: "Malli tallennettu.",
  failed:
    "Tallennus epäonnistui. Tarkista kentät ja mahdollinen kaksoiskappale. Jos toinen ylläpitäjä muokkasi mallia, lataa se uudelleen.",
  category: "Tuoteryhmä",
  note: "Kolme aloitusmallia tuoteryhmää kohti. Lisää tarkat versiot erikseen. Tilastot perustuvat malliin yhdistettyihin FI/EUR-ilmoituksiin ja tällä hetkellä valmiisiin kauppoihin koko ajalta. Hinnoissa ei ole toimitusta tai palvelumaksuja. Kunto ja kokoonpano voivat vaihdella; konemallisto ei yksilöi koko kokoonpanoa.",
  unlinked: "Aktiivisia ilmoituksia ilman mallia",
  asking: "Aktiiviset / keskipyynti",
  sold: "Valmiit / keskikauppahinta",
  noData: "Ei tietoa",
  disabled: "Piilotettu",
  manual: "Vanhoja otsikoita ei yhdistetä malleihin automaattisesti.",
};
const sv: typeof en = {
  ...en,
  title: "Produktkatalog",
  search: "Sök produktmodell",
  hint: "Sök modell eller tillverkare. Välj rätt version eller fyll i manuellt.",
  selected: "Katalogmodell vald",
  clear: "Ange manuellt",
  empty: "Inga modeller hittades. Ange uppgifterna manuellt.",
  loading: "Laddar modeller…",
  error: "Katalogen kunde inte laddas. Försök igen eller ange manuellt.",
  previous: "Föregående",
  next: "Nästa",
  brand: "Tillverkare",
  name: "Modell",
  variant: "Version / kapacitet / artikelnummer",
  aliases: "Alternativa sökord",
  active: "Tillgänglig i annonssökningen",
  save: "Spara modell",
  add: "Lägg till modell",
  edit: "Redigera",
  cancel: "Avbryt",
  saved: "Modellen sparades.",
  failed:
    "Kunde inte spara. Kontrollera fälten och dubbletter. Ladda om modellen om den ändrats av en annan administratör.",
  category: "Kategori",
  note: "Tre startmodeller per kategori. Lägg till exakta varianter separat. Statistiken omfattar länkade FI/EUR-annonser och nu slutförda affärer över hela perioden, utan frakt eller avgifter. Skick och konfiguration kan variera; en datorserie identifierar inte hela konfigurationen.",
  unlinked: "Aktiva annonser utan modell",
  asking: "Aktiva / genomsnittligt begärt pris",
  sold: "Slutförda / genomsnittligt pris",
  noData: "Inga data",
  disabled: "Dold",
  manual: "Äldre rubriker matchas inte automatiskt.",
};
export function productCopy(locale: Locale) {
  return locale === "fi" ? fi : locale === "sv" ? sv : en;
}
